//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GonzStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThamGia
    {
        public int MaNV { get; set; }
        public int MaDA { get; set; }
        public System.DateTime NgayVaoDA { get; set; }
        public Nullable<System.DateTime> NgayRaDA { get; set; }
        public string LyDoRaDA { get; set; }
    
        public virtual DuAn DuAn { get; set; }
        public virtual DuAn DuAn1 { get; set; }
        public virtual Nhanvien Nhanvien { get; set; }
        public virtual Nhanvien Nhanvien1 { get; set; }
    }
}
